### ISSUE TITLE
App crashes when adding keystrokes to a recording.

### ISSUE THREAD

**Issue by ascott18** [NickeManarin/ScreenToGif#1022]
1. Take a recording
2. Add keystrokes overlay
3. Crash:
![image](https://user-images.githubusercontent.com/5017521/146581413-48d1378c-9e05-4082-90fa-5306d5763693.png)

I'm unable to get the details, or to send a report, from the crash dialog. The crash dialog itself is completely frozen and disappears after about 3 seconds.

From event viewer:
```
Application: ScreenToGif.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException

Server stack trace: 
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at ScreenToGif.Windows.Editor.KeyStrokesAsync(KeyStrokesViewModel model)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
   at System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(System.Runtime.Remoting.Messaging.Message, Boolean)
   at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(System.Object, System.Runtime.Remoting.Proxies.MessageData ByRef)
   at ScreenToGif.Windows.Editor+KeyStrokesDelegate.EndInvoke(System.IAsyncResult)
   at ScreenToGif.Windows.Editor.KeyStrokesCallback(System.IAsyncResult)
   at System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessageSink)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

```
Faulting application name: ScreenToGif.exe, version: 2.34.1.0, time stamp: 0x6188292e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1348, time stamp: 0x76fcd692
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0xa75c
Faulting application start time: 0x01d7f36808792eb7
Faulting application path: C:\Files\bin\ScreenToGif.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b4d1a869-06a7-49ca-b2ad-a2aa1ac4306e
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by NickeManarin** [comment]
Can you try again with v2.35.2?

**Comment by ascott18** [comment]
I'm unable to reproduce this now, either from the version I originally found it in, nor in the latest 2.36.
