### ISSUE TITLE
[Bug] Program do NOT launch on arm64

### ISSUE THREAD

**Issue by gxj8885718** [NickeManarin/ScreenToGif#1032]
**Describe the bug**
either github release nor windows store edition, can't open screentogif.
runtime installed.
just process, no windows

**Desktop (please complete the following information):**
 - system:windows 10 21H2
 - device:huawei matebook e 2019
 - architecture:arm64
 - screentogif version:2.35.2

![image](https://user-images.githubusercontent.com/6293425/147453823-2f1e15d3-25ad-4fcc-935c-e4dfe71caa89.png)

**Comment by gxj8885718** [comment]
PS: 2.34.1 works fine.

**Comment by NickeManarin** [comment]
Hi, any error in the event viewer?

![image](https://user-images.githubusercontent.com/14798947/147474092-c5cdf6d8-dea2-4468-9a01-a410faf09146.png)

**Comment by gxj8885718** [comment]
just clear all logs and start screentogif,then refresh windws log, nope, it's empty, nothing logged.
![image](https://user-images.githubusercontent.com/6293425/147478044-c7c1cd70-05ee-415a-a3a4-3114ddd564d8.png)

**Comment by gxj8885718** [comment]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/6293425/147478203-cfd2b1dd-fbd9-4c11-86a5-192535c86384.png">

**Comment by gxj8885718** [comment]
![image](https://user-images.githubusercontent.com/6293425/147478322-084c3903-53b8-4bd6-a754-2b37adbe49dc.png)
runtime installed

**Comment by NickeManarin** [comment]
Thanks.
In the folder where the app is installed, are there any logs?

It's usually inside a folder, like ScreenToGif (install folder) > ScreenToGif > Logs.
Or inside Users > User > Documents > ScreenToGif.

**Comment by gxj8885718** [comment]
Here's the log(under /users/username/documents/screentogif
-------------------------------------------------------
► Title - 
	On dispacher unhandled exception - Unknown
▬ Message - 
	试图加载格式不正确的程序。 (0x8007000B)
○ Type - 
	System.BadImageFormatException
♦ [Version] Date/Hour - 
	[2.35.2] 12/28/2021 19:04:00
▲ Source - 
	PresentationCore
▼ TargetSite - 
	Void RenderOptions_ForceSoftwareRenderingModeForProcess(Boolean)
► Fuslog - 
	
♠ StackTrace - 
   at MS.Win32.PresentationCore.UnsafeNativeMethods.MilCoreApi.RenderOptions_ForceSoftwareRenderingModeForProcess(Boolean fForce)
   at System.Windows.Media.RenderOptions.set_ProcessRenderMode(RenderMode value)
   at ScreenToGif.App.App_Startup(Object sender, StartupEventArgs e) in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif\App.xaml.cs:line 156
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

----------------------------------

► Title - 
	Error while displaying the error.
▬ Message - 
	Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
○ Type - 
	System.Windows.Markup.XamlParseException
♦ [Version] Date/Hour - 
	[2.35.2] 12/28/2021 19:04:00
▲ Source - 
	PresentationFramework
▼ TargetSite - 
	Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
♠ StackTrace - 
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ScreenToGif.Windows.Other.ExceptionDialog.InitializeComponent() in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif\Windows\Other\ExceptionDialog.xaml:line 1
   at ScreenToGif.Windows.Other.ExceptionDialog..ctor(Exception exception) in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif\Windows\Other\ExceptionDialog.xaml.cs:line 21
   at ScreenToGif.Windows.Other.ExceptionDialog.Ok(Exception exception, String title, String instruction, String observation, Boolean bugWith4055002) in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif\Windows\Other\ExceptionDialog.xaml.cs:line 101
   at ScreenToGif.App.<>c__DisplayClass21_0.<ShowException>b__0() in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif\App.xaml.cs:line 433
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at ScreenToGif.App.ShowException(Exception exception) in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif\App.xaml.cs:line 428
   at ScreenToGif.App.App_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif\App.xaml.cs:line 238

▬▬ Message - 
	试图加载格式不正确的程序。 (0x8007000B)
○○ Type - 
	System.BadImageFormatException
▲▲ Source - 
	PresentationCore
▼▼ TargetSite - 
	Void .ctor(System.Windows.Media.MediaContext)
♠♠ StackTrace - 
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)

----------------------------------

**Comment by NickeManarin** [comment]
The logs tell me that at least one DLL from a different assembly is trying to get loaded, which causes the error (bad image).

**Comment by gxj8885718** [comment]
clean install Windows 10 Pro 21H2 , nothing modified. All drivers from stock system image. no strange software installed.

**Comment by NickeManarin** [comment]
Hi, can you try this one?
It's working for me at least.

[ScreenToGif.zip](https://github.com/NickeManarin/ScreenToGif/files/7790761/ScreenToGif.zip)

**Comment by gxj8885718** [comment]
> Hi @gxj8885718, can you try this one? It's working in here.
> 
> [ScreenToGif.zip](https://github.com/NickeManarin/ScreenToGif/files/7790761/ScreenToGif.zip)

Wonderful!! it works!! Great job!

**Comment by NickeManarin** [comment]
Thank you!

**Comment by NickeManarin** [comment]
Version 2.35.3 should be working then.
