### ISSUE TITLE
Error when using x264 encoder

### ISSUE THREAD

**Issue by Roemer** [NickeManarin/ScreenToGif#107]
I tried using the x264 VFW encoder (https://sourceforge.net/projects/x264vfw/) and when encoding with it, I get the following error:

**Win32Exception**
**BadFormat**

>    at ScreenToGif.FileWriters.AviWriter..ctor(String path, Int32 frameRate, Int32 width, Int32 height, UInt32 quality)
>    at ScreenToGif.Windows.Other.Encoder.Encode(List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource)

**Comment by NickeManarin** [comment]
I downloaded, installed (checked both x86 and x64) and saved the video successfully.

Btw, I have 64 bits system.

> From what I understand, an assembly specifically built for x86 and running in a 64-bit operating system can only load libraries built for x86 or a BadImageFormatException will be thrown. In a 64-bit OS, an assembly built for Any CPU or x64 will throw the same exception when trying to load an x86 library.
[Source](http://stackoverflow.com/a/2728678/1735672)

**Comment by koppor** [comment]
I found this page when googling for "bei ScreenToGif.Windows.Other.Encoder.Encode(List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource)". Possibly unrelated, because I am using ffmpeg installed via `choco install ffmpeg`.

![grafik](https://cloud.githubusercontent.com/assets/1366654/25423396/d702ceee-2a64-11e7-9caf-ac419c142b39.png)

Also Win10, 64bit

**Comment by NickeManarin** [comment]
@koppor Can you copy and paste here the text from the other window that opens if you click on "Ausnahme" (top-right corner)?

With the next version of ScreenToGif, encoding with FFmpeg should be easier, I replaced the default "Extra" parameter with a more common set of parameters.

**Comment by AlexFielder** [comment]
Hi @NickeManarin I'm not sure if you have changed the settings from when @koppor replied but I too am getting a similar error with a chocolatey-installed version of ffmpeg:`   at ScreenToGif.Windows.Other.Encoder.Encode(List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource)

ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: 
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
Input #0, concat, from 'C:\Users\Alex.Fielder\AppData\Local\Temp\ScreenToGif\Recording\2017-06-29 16-22-55\Encode 2017-06-29 05-10-39\concat.txt':
  Duration: 00:00:51.46, start: 0.000000, bitrate: 14 kb/s
    Stream #0:0: Video: png, rgba(pc), 1936x1015 [SAR 3779:3779 DAR 1936:1015], 25 tbr, 25 tbn, 25 tbc
Unknown encoder 'libx264'`

**Comment by NickeManarin** [comment]
Ok, let's analyze this:

@Roemer Can you tell me which version of the **x264 VFW encoder** did you install? I installed both 32bits and 64 bits and it was working.

@koppor Your post was a little bit unrelated indeed. This issue ticket is related to the **System**  encoder and not the **FFmpeg** encoder. Anyway, with version 2.11 of ScreenToGif, can you save as a video successfully?

@AlexFielder I did change something from that older release to the one that you used, one of the changes involved the addition of the "Extras" field where these new parameters were added. Do you remember if the FFmpeg version that you had was compiled with the flag **--enable-libx264**?

**Comment by dogancelik** [comment]
I got the same error, here's the exception:

```
   at ScreenToGif.ImageUtil.Video.AviWriter..ctor(String path, Int32 frameRate, Int32 width, Int32 height, UInt32 quality)
   at ScreenToGif.Windows.Other.Encoder.<Encode>d__22.MoveNext()
```

I have both 32-bit and 64-bit versions installed.

1. Image: [32-bit](https://user-images.githubusercontent.com/486818/48881269-7d687b00-ee25-11e8-883a-1fe86ed8d2b6.PNG)
2. Image: [64-bit](https://user-images.githubusercontent.com/486818/48881268-7d687b00-ee25-11e8-84f8-0df7edb135b0.PNG)

**Comment by NickeManarin** [comment]
Closing this due to inactivity.
