### ISSUE TITLE
[Bug] Can't use DirectX capture method

### ISSUE THREAD

**Issue by 7peanuts** [NickeManarin/ScreenToGif#1161]
**Describe the bug**
Hi, I can't use directX capture method, whether it is capturing the whole screen or part of the screen, but it still work with the BitBlt capture method.
Here is the error message:

![20221206105526](https://user-images.githubusercontent.com/82173614/205798455-acb0373e-78fe-4fa4-8dfa-a6bbaba2aa4b.jpg)

`   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at System.Threading.Tasks.Task.Dispose()
   at ScreenToGif.Capture.BaseCapture.DisposeInternal() in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Capture\BaseCapture.cs:line 175
   at ScreenToGif.Capture.BaseCapture.DisposeAsync() in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Capture\BaseCapture.cs:line 184
   at ScreenToGif.Windows.NewRecorder.PrepareCapture(Boolean isNew) in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Windows\NewRecorder.xaml.cs:line 1394
   at ScreenToGif.Windows.NewRecorder.Record() in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Windows\NewRecorder.xaml.cs:line 1033`

**Desktop (please complete the following information):**
Windows 11 22H2 22621.900
Windows Feature Experience Pack 1000.22638.1000.0
Graphics Card: AMD 5700XT Adrenalin 22.5.1 Recommended (WHQL)
ScreenToGif version: 2.37.1

**Comment by 7peanuts** [comment]
Sorry, it's ready. Something is wrong with my graphics driver 😂
