### ISSUE TITLE
Error while encoding the MP4, Mov... with FFmpeg.

### ISSUE THREAD

**Issue by jotakar** [NickeManarin/ScreenToGif#1229]
Hello
Windows 11
I get this error when I try to save as no AVI videos format 
With MP4 I get this details
   at ScreenToGif.Util.EncodingManager.EncodeWithFfmpeg(ExportPreset preset, List`1 listFrames, Int32 id, CancellationTokenSource tokenSource, String processing) in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1742
   at ScreenToGif.Util.EncodingManager.Encode(ExportProject project, ExportPreset preset, Int32 id, CancellationTokenSource tokenSource) in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1037

Command:

-vsync vfr -hwaccel auto -safe 0 -f concat -i "file:C:\Users\jcgar\AppData\Local\Temp\ScreenToGif\Recording\2023-09-19 14-07-38\Encode 2023-09-19 02-28-22-87\concat.txt" -c:v libx264 -preset fast -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -b:v 15M -maxrate 25M -bufsize 8M -pass 1 -passlogfile "E:\borrar\creasitio3.mp4" -r 40 -f mp4 -y "E:\borrar\creasitio3.mp4"
-hide_banner -vsync vfr -hwaccel auto -safe 0 -f concat -i "file:C:\Users\jcgar\AppData\Local\Temp\ScreenToGif\Recording\2023-09-19 14-07-38\Encode 2023-09-19 02-28-22-87\concat.txt" -c:v libx264 -preset fast -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -b:v 15M -maxrate 25M -bufsize 8M -pass 2 -passlogfile "E:\borrar\creasitio3.mp4" -r 40 -f mp4 -y "E:\borrar\creasitio3.mp4"

Result:

ffmpeg version N-102355-g1caf09a71a-gd055af5e7b+1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev1, Built by MSYS2 project)
  configuration:  --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --ld='ccache g++' --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-schannel --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  0.100 / 59.  0.100
  libavformat    59.  0.101 / 59.  0.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.101 /  8.  0.101
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
Input #0, concat, from 'file:C:\Users\jcgar\AppData\Local\Temp\ScreenToGif\Recording\2023-09-19 14-07-38\Encode 2023-09-19 02-28-22-87\concat.txt':
  Duration: 00:00:13.67, start: 0.000000, bitrate: 16 kb/s
  Stream #0:0: Video: png, rgba(pc), 741x763 [SAR 3779:3779 DAR 741:763], 25 fps, 25 tbr, 25 tbn
Unknown encoder 'libx264'

Input #0, concat, from 'file:C:\Users\jcgar\AppData\Local\Temp\ScreenToGif\Recording\2023-09-19 14-07-38\Encode 2023-09-19 02-28-22-87\concat.txt':
  Duration: 00:00:13.67, start: 0.000000, bitrate: 16 kb/s
  Stream #0:0: Video: png, rgba(pc), 741x763 [SAR 3779:3779 DAR 741:763], 25 fps, 25 tbr, 25 tbn
Unknown encoder 'libx264'

**Comment by jotakar** [comment]
Solved. I reinstall ffmpeg.
