### ISSUE TITLE
[Bug] A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).

### ISSUE THREAD

**Issue by 3119369616** [NickeManarin/ScreenToGif#1232]
**Describe the bug**

## A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
```text
   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at System.Threading.Tasks.Task.Dispose()
   at ScreenToGif.Capture.BaseCapture.DisposeInternal() in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Capture\BaseCapture.cs:line 175
   at ScreenToGif.Capture.BaseCapture.DisposeAsync() in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Capture\BaseCapture.cs:line 184
   at ScreenToGif.Windows.NewRecorder.PrepareCapture(Boolean isNew) in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Windows\NewRecorder.xaml.cs:line 1394
   at ScreenToGif.Windows.NewRecorder.Record() in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Windows\NewRecorder.xaml.cs:line 1033
```
**To Reproduce**
1. Go into the "recorder".
2. Press <kbd>F7</kbd>.
3. See error

**Expected behavior**
Record my screen properly.

**Screenshots**
![image](https://github.com/NickeManarin/ScreenToGif/assets/38552079/5b399407-4ee3-46c5-8ccd-84531092198d)
![image](https://github.com/NickeManarin/ScreenToGif/assets/38552079/e777ad4e-afe0-4f96-8dff-a931983cd542)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 22H2

**Additional context**

**Comment by 3119369616** [comment]
This is the similar issue to #1161.

**Comment by pawlos** [comment]
The top of the stacktrace is similar also to this issue #1225. I've tried to repro this in some way but never got any issues.
