### ISSUE TITLE
Error message when accessing Editor!

### ISSUE THREAD

**Issue by alphestdev** [NickeManarin/ScreenToGif#234]
A few days ago everything worked fine. But after recent Windows Update ScreenToGif 2.11 does not allow me to enter Editor. It crashes with an error message.

![screentogif 2 11 error](https://user-images.githubusercontent.com/32202/34855107-311d3f62-f73e-11e7-81ae-8ee9bae7cece.png)

[ScreenToGif Raw Error.txt](https://github.com/NickeManarin/ScreenToGif/files/1624661/ScreenToGif.Raw.Error.txt)

Windows 7 x64

**Comment by NickeManarin** [comment]
Can you send me the full log? It should be inside a folder structure like "ScreenToGif/Logs" on the same folder where the app is located or inside the documents folder.

If you don't find that folder and the logs, can you press the button "Open Inner Exception" and copy-paste it here?

**Comment by alphestdev** [comment]
Ofcourse. All the info I can find:

Parent error window looks like this:
![screentogif parent error window](https://user-images.githubusercontent.com/32202/34895698-297fc4f6-f7e7-11e7-8e68-9d54d9aa31d5.png)

"Open Inner Exception" gives this:
![screentogif inner exception](https://user-images.githubusercontent.com/32202/34895778-71553ebe-f7e7-11e7-8ef4-cf5e2c0a1066.png)
 
Paste:
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
```
The log from "ScreenToGif/Logs" 
[18_01_12.txt](https://github.com/NickeManarin/ScreenToGif/files/1627562/18_01_12.txt)


Both portable and installed version have this. Deleting settings file and letting ScreenToGif generate a clean one does not help.

**Comment by NickeManarin** [comment]
Oh, thank you for the fast reply. :)

I was reading the messages that were sent by the feedback tool and I noticed that I've already got a report about this same issue.

So, this is basically an issue with the latest update of .Net Framework (January 2018, KB4074906).
The only way to fix it is by uninstalling that faulty update. 

You can read more about this issue on this page:
https://github.com/dotnet/announcements/issues/53

**Comment by alphestdev** [comment]
@NickeManarin Thanks for the find!
