### ISSUE TITLE
'System.Windows.Markup.StaticExtension' threw an exception.

### ISSUE THREAD

**Issue by deePerl** [NickeManarin/ScreenToGif#312]
1. I download the portable version release 2.13
2. I double click on the exe
3. I click on "Recorder"
4. I click on "Record"
5. I wait some seconds
6. I Click on "Stop"
7. I get an `XamlParserException` exception: 

`Provide value on 'System.Windows.Markup.StaticExtension' threw an exception.`
```
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at ScreenToGif.Windows.Editor..ctor()
   at ScreenToGif.Util.Model.ApplicationViewModel.ShowEditor(ProjectInfo project)
   at ScreenToGif.Util.Model.ApplicationViewModel.<>c__DisplayClass3_0.<get_OpenRecorder>b__3(Object sender, EventArgs args)
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by NickeManarin** [comment]
Hi, this is caused by a bug with the January 2018 update of .Net Framework 4.7.1 for Windows 7 SP1

Here:

https://github.com/NickeManarin/ScreenToGif/issues/257
