### ISSUE TITLE
The change of username crashed App

### ISSUE THREAD

**Issue by hanzhangyu** [NickeManarin/ScreenToGif#400]
The App broken when I use record after I change my computer name, and I got the same result after reinstall it

```
► Title - 
	On Dispacher Unhandled Exception - Unknown
▬ Message - 
	对路径“C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Recording\2018-11-29 21-21-43\”的访问被拒绝。
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.12.1] 11/29/2018 21:21:43
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   在 System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   在 ScreenToGif.Util.Model.ProjectInfo.CreateProjectFolder()
   在 ScreenToGif.Windows.Recorder.<RecordPause>d__54.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

----------------------------------

► Title - 
	Check for an updated localization recource
▬ Message - 
	Access to the path 'C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Localization' is denied.
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.14.1] 11/29/2018 21:23:11
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ScreenToGif.Util.LocalizationHelper.CheckForUpdates(String culture)

----------------------------------

► Title - 
	On Dispacher Unhandled Exception - Unknown
▬ Message - 
	Access to the path 'C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Recording\2018-11-29 21-23-13\' is denied.
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.14.1] 11/29/2018 21:23:13
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ScreenToGif.Model.ProjectInfo.CreateProjectFolder(ProjectByType creator)
   at ScreenToGif.Windows.Recorder.<RecordPause>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

----------------------------------

► Title - 
	Check for an updated localization recource
▬ Message - 
	Access to the path 'C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Localization' is denied.
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.14.1] 11/29/2018 21:24:04
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ScreenToGif.Util.LocalizationHelper.CheckForUpdates(String culture)

----------------------------------

► Title - 
	On Dispacher Unhandled Exception - Unknown
▬ Message - 
	Access to the path 'C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Recording\2018-11-29 21-24-07\' is denied.
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.14.1] 11/29/2018 21:24:07
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ScreenToGif.Model.ProjectInfo.CreateProjectFolder(ProjectByType creator)
   at ScreenToGif.Windows.Recorder.<RecordPause>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

----------------------------------

► Title - 
	Check for an updated localization recource
▬ Message - 
	Access to the path 'C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Localization' is denied.
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.14.1] 11/29/2018 21:24:18
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ScreenToGif.Util.LocalizationHelper.CheckForUpdates(String culture)

----------------------------------

► Title - 
	Check for an updated localization recource
▬ Message - 
	Access to the path 'C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Localization' is denied.
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.14.1] 11/29/2018 21:25:42
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ScreenToGif.Util.LocalizationHelper.CheckForUpdates(String culture)

----------------------------------

► Title - 
	On Dispacher Unhandled Exception - Unknown
▬ Message - 
	Access to the path 'C:\Users\zhang\AppData\Local\Temp\ScreenToGif\Recording\2018-11-29 21-25-45\' is denied.
○ Type - 
	System.UnauthorizedAccessException
♦ [Version] Date/Hour - 
	[2.14.1] 11/29/2018 21:25:45
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ScreenToGif.Model.ProjectInfo.CreateProjectFolder(ProjectByType creator)
   at ScreenToGif.Windows.Recorder.<RecordPause>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

----------------------------------


```

**Comment by hanzhangyu** [comment]
em, Everything goes fine after deleted setting in `Roaming`

**Comment by NickeManarin** [comment]
Thanks for the feedback. I'll add a warning explaining that the location of the temporary files is inaccessible and it needs to be changed.

Let's keep this issue open until I finish it.

**Comment by smaragdus** [comment]
Another reason to use the program in portable mode.
