### ISSUE TITLE
Setting lost after save as video file extention change

### ISSUE THREAD

**Issue by jburdy** [NickeManarin/ScreenToGif#420]
If I change the extention of the video (avi to mp2 for example) I lost all my parameters after restart the app ! If I do other change, all is ok.

Version 2.15.1

This is the log :
-----
► Title - 
	Saving settings
▬ Message - 
	Object reference not set to an instance of an object.
○ Type - 
	System.NullReferenceException
♦ [Version] Date/Hour - 
	[2.15.1] 01/04/2019 10:10:42
▲ Source - 
	mscorlib
▼ TargetSite - 
	System.Type GetType()
♠ StackTrace - 
   at System.Object.GetType()
   at System.Windows.Markup.Primitives.ElementMarkupObject.get_ObjectType()
   at System.Windows.Markup.Primitives.MarkupWriter.RecordNamespaces(Scope scope, MarkupObject item, IValueSerializerContext context, Boolean lastWasString)
   at System.Windows.Markup.Primitives.MarkupWriter.RecordNamespaces(Scope scope, MarkupObject item, IValueSerializerContext context, Boolean lastWasString)
   at System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item)
   at System.Windows.Markup.Primitives.MarkupWriter.SaveAsXml(XmlWriter writer, MarkupObject item)
   at System.Windows.Markup.XamlWriter.Save(Object obj, XmlWriter xmlWriter)
   at ScreenToGif.Util.UserSettings.Save()

**Comment by NickeManarin** [comment]
How exactly did you change the video extension from avi to mp2?

**Comment by NickeManarin** [comment]
I believe this bug was fixed this year. 
I'm closing this issue, but if you still get the same error, I'll reopen it.
