### ISSUE TITLE
Can't run it on win10 1903

### ISSUE THREAD

**Issue by KIRIZAMERAN** [NickeManarin/ScreenToGif#525]
**NET.Framework version：4.8.0
System：Windows10 1903
Language：Simplified Chinese
Error information：**

Unhandled exception

Set property 'ScreenToGif.Controls.NotifyIcon.IconSource' threw an exception.

at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.Application.FindResource(Object resourceKey)
   at ScreenToGif.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mrfearless** [comment]
same as #388

**Comment by NickeManarin** [comment]
Strange, the only place where I change the icon is right at the beginning of the app:

Like this: `IconSource="/Resources/Logo.ico"`

Are you running your Windows at a different color space than 32bits?
I'm going to add some checks to avoid the crash, at least.

**Comment by NickeManarin** [comment]
Can you test if it works?

[ScreenToGif_Test.zip](https://github.com/NickeManarin/ScreenToGif/files/3687557/ScreenToGif_Test.zip)

**Comment by mrfearless** [comment]
It opens without any errors or messages displayed. Goes straight to the startup screen. The notification icon is blank - as in, it appears along side other icons (i noticed the shuffle as it added itself) in the tray notification area, but no icon is showing - just a fully transparent icon or space for where an icon would be.

**Comment by NickeManarin** [comment]
Thank you. At least it opens now.

Now I need to understand why my icon is not loading.
It's strange because the file is attached to the executable and is the same that appears in the taskbar and in the executable file in the Windows Explorer. I'm assuming that you can see the ScreenToGif icon on your taskbar and in the executable file.

[ScreenToGif_Test_2.zip](https://github.com/NickeManarin/ScreenToGif/files/3687872/ScreenToGif_Test_2.zip)
Here's another with a slightly changed initialization behavior.
If it still does not work, I'll have to export the icon again, exporting as 256 colors too.

**Comment by KIRIZAMERAN** [comment]
test 1 open without error but icon problem same as mrfearless
test 2 open with error message：
the app crashed

 System.Drawing.Initialize
  at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at ScreenToGif.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by NickeManarin** [comment]
Thank you. Same crash, looks like it's the same reason.
It's hard to know exactly what's wrong, specially without having a computer having the same crash.
I added the icon with 256 colors too.

[ScreenToGif_Test_3.zip](https://github.com/NickeManarin/ScreenToGif/files/3688042/ScreenToGif_Test_3.zip)

**Comment by mrfearless** [comment]
Test 2 crashed, Test 3 works, but icon is blank in tray - same as Test 1

**Comment by NickeManarin** [comment]
Stack trace from @mrfearless 

```
► Title - 
	On Dispacher Unhandled Exception - Unknown
▬ Message - 
	Set property 'ScreenToGif.Controls.NotifyIcon.IconSource' threw an exception.
○ Type - 
	System.Windows.Markup.XamlParseException
♦ [Version] Date/Hour - 
	[2.13.3] 10/16/2018 10:55:46
▲ Source - 
	PresentationFramework
▼ TargetSite - 
	Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
♠ StackTrace - 
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.Application.FindResource(Object resourceKey)
   at ScreenToGif.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

▬▬ Message - 
	The operation completed successfully
○○ Type - 
	System.ComponentModel.Win32Exception
▲▲ Source - 
	System.Drawing
▼▼ TargetSite - 
	Void Initialize(Int32, Int32)
♠♠ StackTrace - 
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at ScreenToGif.ImageUtil.ImageMethods.ToIcon(ImageSource imageSource)
   at ScreenToGif.Controls.NotifyIcon.IconSourcePropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
```

**Comment by NickeManarin** [comment]
From what I know about this error, it's Windows telling the user that it can't load anything else.
Too many GDI objects were already loaded.

If this issue happens again with you people, can you open Task Manager and go to Details, and right click on the header of the data grid, enable GDI objects and see if there's a process eating too much GDI objects.
