### ISSUE TITLE
Crash: The requested security protocol is not supported.

### ISSUE THREAD

**Issue by giantmustache** [NickeManarin/ScreenToGif#590]
At the moment I start ScreenToGif I receive an error. Then the program closes down. It seems that something is not supported, although it is unclear to me what to do about it.

I used the single executable, because the installer crashed for the same reason and I hoped that this would work out for me. I have attached the log. Is there any other information you would like to have from me?

► Title - 
	On dispacher unhandled exception - Unknown
▬ Message - 
	The requested security protocol is not supported.
○ Type - 
	System.NotSupportedException
♦ [Version] Date/Hour - 
	[2.20.3] 02/18/2020 11:06:31
▲ Source - 
	System
▼ TargetSite - 
	Void ValidateSecurityProtocol(System.Net.SecurityProtocolType)
♠ StackTrace - 
   at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   at ScreenToGif.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

----------------------------------

**Comment by Bliamoh** [comment]
I have the same issue when I'm trying to install the last version (2.20.3) with the installer or with the portable version. I just downloaded the 2.20.2 version and the error didn't appear. Some changes in the 2.20.3 version must cause it.
I'm on Windows 10 x64.

**Comment by giantmustache** [comment]
I have some more info after I got @Bliamoh 's comment. I got 2.20.3 working as follows:

- I received the error when using 2.20.3 portable
- I deleted 2.20.3 portable
- I installed 2.20.2 portable
- I received the notification that I didn't have .NET 4.8 installed. So I installed it.
- I restarted my machine. 2.20.2 portable is working fine.
- I deleted 2.20.2 portable
- I installed 2.20.3 portable. This version is now working fine as well.

So it seems that not having .NET 4.8 installed on your machine lets the application crash and doesn't ask me for downloading it.

**Comment by NickeManarin** [comment]
@giantmustache Yes, it's a know bug. Sorry.

The app is crashing because the .NET Framework 4.8 is not installed before the message is able to appear. 
I already fixed it and I'm going to launch a new version next weekend.

**Comment by NickeManarin** [comment]
I added a warning on screentogif.com and I also pinned this issue.
