### ISSUE TITLE
Removes all user settings

### ISSUE THREAD

**Issue by lukaszmn** [NickeManarin/ScreenToGif#639]
When I started it today, it removed all my settings. After I set a few options:
* language: English
* one saving preset for mp4
* location for ffmpeg

it doesn't save any options, and prints the following error to the log file:

```
► Title - 
	Saving settings
▬ Message - 
	Object reference not set to an instance of an object.
○ Type - 
	System.NullReferenceException
♦ [Version] Date/Hour - 
	[2.23.1] 04/20/2020 05:07:11
▲ Source - 
	mscorlib
▼ TargetSite - 
	System.Type GetType()
♠ StackTrace - 
   at System.Object.GetType()
   at System.Windows.Markup.Primitives.ElementMarkupObject.get_ObjectType()
   at System.Windows.Markup.Primitives.MarkupWriter.RecordNamespaces(Scope scope, MarkupObject item, IValueSerializerContext context, Boolean lastWasString)
   at System.Windows.Markup.Primitives.MarkupWriter.RecordNamespaces(Scope scope, MarkupObject item, IValueSerializerContext context, Boolean lastWasString)
   at System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item)
   at System.Windows.Markup.Primitives.MarkupWriter.SaveAsXml(XmlWriter writer, MarkupObject item)
   at System.Windows.Markup.XamlWriter.Save(Object obj, XmlWriter xmlWriter)
   at ScreenToGif.Util.UserSettings.Save()
```

What's worse, it also deletes the backup file.

**Comment by bNobo** [comment]
I was not able to reproduce this issue. Could you provide steps to reproduce the error ?

**Comment by lukaszmn** [comment]
Assumptions:

1. ffmpeg is downloaded and set in the ScreenToGif config

Steps:

1. Record a short movie
2. Click Save As
3. Select Video > FFmpeg
3. Select a file with `.mp4` extension
4. Add a new Preset
   * name: `abc`
   * value: `-pix_fmt yuv420p -force_key_frames expr:gte(t,n_forced/2) -c:v libx264 -crf 18 -bf 2 -use_editlist 0 -movflags +faststart -vf "scale=-2:720:flags=lanczos"`
5. Save the Preset
6. Close the application

Result:

`C:\Users\...\AppData\Roaming\ScreenToGif\Settings.xaml` has size of 3 bytes.

**Comment by bNobo** [comment]
Thank you @lukaszm, I was able to reproduce the exception with your detailed explanation. It seems the problem comes when selecting the .mp4 extension. I've proposed a pull request to solve it.

**Comment by NickeManarin** [comment]
Thank you @bNobo and @lukaszmn !
