### ISSUE TITLE
Error while encoding the video with FFmpeg

### ISSUE THREAD

**Issue by ashishpatel1992** [NickeManarin/ScreenToGif#654]
Not able to export any video using ffmpeg
**Error while encoding the video with FFmpeg.**
```
   at ScreenToGif.Windows.Other.Encoder.EncodeWithFfmpeg(String name, List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource, String processing)
   at ScreenToGif.Windows.Other.Encoder.<Encode>d__26.MoveNext()

Command:

-vsync 2 -safe 0 -f concat -i "C:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-13-42-41\concat.txt" -f matroska -c:v libx265 -b:v 1M -g 150 -pix_fmt yuv420p -vf "pad=width=1366:height=768:x=0:y=0:color=black" -y "C:\Users\Diksha\Desktop\insta post\tutorial32.mkv"


Result:


ffmpeg version git-2020-05-10-fc99a24 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 44.100 / 56. 44.100
  libavcodec     58. 83.100 / 58. 83.100
  libavformat    58. 43.100 / 58. 43.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 80.100 /  7. 80.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[concat @ 000001df5dfec600] Impossible to open 'CC:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-13-42-41\0.png'
C:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-13-42-41\concat.txt: Protocol not found
Did you mean file:C:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-13-42-41\concat.txt?
```

**Comment by NickeManarin** [comment]
[ScreenToGif_Test.zip](https://github.com/NickeManarin/ScreenToGif/files/4629492/ScreenToGif_Test.zip)

Can you run this version, and try exporting some video with FFmpeg? 

It should open a folder, before pressing OK to continue, open the concat.txt file and paste the first lines in here.

**Comment by ashishpatel1992** [comment]
This time I got a popup message and opened a folder asking me to check file inside the folder with concat.txt and as soon as I clicked Ok to continue, The files automatically got removed and folder closed and got following error

```
   at ScreenToGif.Windows.Other.Encoder.EncodeWithFfmpeg(String name, List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource, String processing)
   at ScreenToGif.Windows.Other.Encoder.<Encode>d__26.MoveNext()

Command:

-vsync 2 -safe 0 -f concat -i "C:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-44-15-06\concat.txt" -c:v libx264 -b:v 1M -g 150 -pix_fmt yuv420p -tile-columns 6 -frame-parallel 1 -vf "pad=width=1366:height=768:x=0:y=0:color=black" -y "C:\Users\Diksha\Desktop\insta post\tutorialXX.mp4"


Result:


ffmpeg version git-2020-05-10-fc99a24 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 44.100 / 56. 44.100
  libavcodec     58. 83.100 / 58. 83.100
  libavformat    58. 43.100 / 58. 43.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 80.100 /  7. 80.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[concat @ 000001a99d36cd80] Impossible to open 'CC:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-44-15-06\0.png'
C:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-44-15-06\concat.txt: Protocol not found
Did you mean file:C:\Users\Diksha\AppData\Local\Temp\ScreenToGif\Recording\2020-05-14 19-12-42\Encode 2020-05-14 09-44-15-06\concat.txt?
```

**Comment by NickeManarin** [comment]
> before pressing OK to continue, open the concat.txt file and paste the first lines in here.

**Comment by NickeManarin** [comment]
I got the same error now. Something must have changed with FFmpeg.

**Comment by NickeManarin** [comment]
Fixed. I'm going to launch a new version with a fix for this bug.
If you can wait, download version 4.2.2 of FFmpeg from zeranoe.
