### ISSUE TITLE
New recorder. Area / window selection.

### ISSUE THREAD

**Issue by wvxwxvw** [NickeManarin/ScreenToGif#713]
When trying to select an area, window or screen, the program crashes.

ScreenToGif 2.27 Portable, Windows 7

**Comment by wvxwxvw** [comment]
Works fine on previous versions. Now I checked it specially.

**Comment by NickeManarin** [comment]
I need to know the exception details. Does it display an error message or anything?

**Comment by wvxwxvw** [comment]
Sorry.
WindowsBase.SetValueCommon
`   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at ScreenToGif.Windows.Other.RegionSelector.Select(Monitor monitor, ModeType mode, Rect previousRegion, Action`2 selected, Action`1 changed, Action`1 gotHover, Action aborted)
   at ScreenToGif.Capture.RegionSelectHelper.Select(ModeType mode, Rect previousRegion, Monitor currentMonitor, Boolean quickSelection)
   at ScreenToGif.Windows.NewRecorder.<PickRegion>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScreenToGif.Windows.NewRecorder.<RegionButton_Click>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by NickeManarin** [comment]
Thanks, and the exception type and message?

**Comment by NickeManarin** [comment]
System.ArgumentException
  HResult=0x80070057
  Message='∞' is not a valid value for property 'Width'.
  Source=WindowsBase

Something like this?
If so, are you using Windows 7?

**Comment by wvxwxvw** [comment]
> '∞' is not a valid value for property 'Width'.

Yes.

> If so, are you using Windows 7?

Yes, in the first post it is written.

**Comment by NickeManarin** [comment]
> Yes, in the first post it is written.

Ooops. I forgot about it. :/

Anyway, I believe that fixed this issue.
It was caused by the code that detects the system DPI.
I was using an API exclusive to Windows 8 and newer.

**Comment by wvxwxvw** [comment]
OK
