### ISSUE TITLE
Download ffmpeg fails while resolving zeranoe.com

### ISSUE THREAD

**Issue by ndrwrbgs** [NickeManarin/ScreenToGif#777]
The remote name could not be resolved: 'ffmpeg.zeranoe.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScreenToGif.Windows.Options.<FfmpegImageCard_Click>d__69.MoveNext()

**Comment by NickeManarin** [comment]
Hi, always update to the latest version to check if the bugs still exist or not.
This was fixed already. :)

**Comment by ndrwrbgs** [comment]
Oh shoot, I checked for latest version in ANOTHER app and thought I had done it in this one.
I tried to do that, just did it wrong :)

**Comment by NickeManarin** [comment]
It's all right. In the latest versions, the updater was reworked. You can enable automatic updates if you wish.
