### ISSUE TITLE
v2.27.3.0 "The calling thread must be STA" per-frame exception

### ISSUE THREAD

**Issue by wizzard0** [NickeManarin/ScreenToGif#809]
**Details**
During full-screen recording, after switching apps a number of times, I get an 'Unhandled exception' window each frame.
Errors stop after pressing F7 to stop recording.

**STR**:
Fastest way to reproduce (5-10 clicks) is to switch between Notepad and a website pinned as an app in Microsoft Edge, trying to simultaneously type something in either window.

**Machine**:

```
Win10 10.0.19042.0, 16G RAM
Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
NVIDIA GeForce GTX 965M @ 59Hz v27.21.14.5167
Intel(R) HD Graphics 520 @ 59Hz v24.20.100.6293
ScreenToGif v2.27.3.0
```

**Monitor**:
3840x2160, "Second screen only" mode, using Intel graphics

**Exception**:
```
► Title - 
	On dispacher unhandled exception - Unknown
▬ Message - 
	The calling thread must be STA, because many UI components require this.
○ Type - 
	System.InvalidOperationException
♦ [Version] Date/Hour - 
	[2.27.3] 03/19/2021 05:21:38
▲ Source - 
	PresentationCore
▼ TargetSite - 
	Void .ctor()
♠ StackTrace - 
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.RoutedCommand.Execute(Object parameter, IInputElement target)
   at ScreenToGif.Windows.NewRecorder.<PrepareNewCapture>b__71_0(Exception exception)
   at ScreenToGif.Capture.DirectImageCapture.CaptureWithCursor(FrameInfo frame)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScreenToGif.Capture.DirectImageCapture.<CaptureWithCursorAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScreenToGif.Windows.NewRecorder.<CursorAsync_Elapsed>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
----------------------------------
```

Other than that, really awesome app! Love the UI and all the details put into it.

**Comment by NickeManarin** [comment]
It looks like there's three issues here:

1) Something deep down in the capture method is triggering an error.
2) Upon receiving an error, the recorder should pause the recording, but it's not.
3) After pausing, a message should appear, indicating the error details of the capture.

**Comment by NickeManarin** [comment]
I have tried to reproduce this, without success.

Try disabling the asynchronous capture under Options > Recorder.

Anyway, I planning in reworking the capture methods, to increase the performance.

**Comment by wizzard0** [comment]
um... but without async capture it's all too slow and the mouse cursor freezes while capturing :/ i tried doing a timelapse of what i'm working on and it's pretty much unusable this way

**Comment by NickeManarin** [comment]
I managed to fix this issue..

Before the update arrives, try using memory cache instead of saving the frames as files in Options > Recorder.
You can still use the async method with the mem. cache option enabled.

**Comment by wizzard0** [comment]
cool, thanks!

**Comment by NickeManarin** [comment]
Just tell me if using the memory cache helped or not :)

**Comment by NickeManarin** [comment]
Are you still getting this issue with the latest version? v2.30
