### ISSUE TITLE
filenotfound - 2.28.2

### ISSUE THREAD

**Issue by joekingTheThird3** [NickeManarin/ScreenToGif#846]
win 7 64bit

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   
   
   mscorlib.CreateInstance

**Comment by joekingTheThird3** [comment]
I look log - log say Unable to load DLL 'Shcore.dll' . win 7 no dll. No possible load shcore.dll on win 7?  copy dll to C:\Windows\System32 . still crash - unhandled exception. clsid 56fdf344-fd6d-11d0-958a-0060 .......

**Comment by joekingTheThird3** [comment]
I used the portable edition.

**Comment by NickeManarin** [comment]
Are you getting a warning on screen or is this just from the log file?

Jus to check, are you using Win 7 SP1?

**Comment by joekingTheThird3** [comment]
Ok, let's enter dll hell.  So, I installed Shcore.dll, then I get loader error. I install the 64 bit version of the VC_redist.x64.exe -  c++ redistributable 64 bit. I must of had the 32bit before. Now I rename shcore.dll to eliminate it from loading and now there are no errors. I assume I had a 32bit version of the c++ redistributable before.

**Comment by joekingTheThird3** [comment]
Ok, after installing the update 2.29, I get no error on prog load but when I go to editor then I seem to be getting the same error from previous. Seems like app is trying to access dll not on win 7.
![Screenshot - 03_05_2021 , 09_22_13](https://user-images.githubusercontent.com/47086018/116855535-75fe4c00-abf1-11eb-9309-f111908ca9dd.png)
![Screenshot - 03_05_2021 , 09_21_57](https://user-images.githubusercontent.com/47086018/116855537-7696e280-abf1-11eb-9547-32318ceeb47b.png)

**Comment by joekingTheThird3** [comment]
![Screenshot - 03_05_2021 , 09_26_51](https://user-images.githubusercontent.com/47086018/116855701-b9f15100-abf1-11eb-82b2-eeeb916847d8.png)

**Comment by rddim** [comment]
Hello,
I have the same issue with missing `SHCore.dll` on W7 x64. I have installed `M$ .Net Framework 4.8`, `M$ VC 2015-2019 redist` x64 and x86, but the issue is fixed when I install the `KB4019990`.

I found this:
`To function properly, .NET 4.8/4.7.2 require D3DCompiler_47.dll component, which is found in either the current "Monthly Quality Rollup" or "update KB4019990"`
