### ISSUE TITLE
[BUG] When I want to save the gif.

### ISSUE THREAD

**Issue by YoucanBaby** [NickeManarin/ScreenToGif#933]
One or more errors occurred.
`   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at ScreenToGif.ImageUtil.ImageMethods.PaintTransparentAndCut(ExportProject project, Color chroma, Int32 taskId, CancellationTokenSource tokenSource)
   at ScreenToGif.Util.EncodingManager.<Encode>d__27.MoveNext()`

Index was outside the bounds of the array.
`   at ScreenToGif.ImageUtil.ImageMethods.<>c__DisplayClass1_1.<PaintTransparentAndCut>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)`
ScreenToGif.<PaintTransparentAndCut>b__0

**Comment by YoucanBaby** [comment]
I solved it. This error occurred because of the inconsistent size of my pictures.

**Comment by NickeManarin** [comment]
Yes, that's it. But how did you create such a project, with multiple sized images?

**Comment by MaReGitHub** [comment]
On my site this happened when I insert a "title picture" to my project at the beginning.

Do you have an idea how to solve?
![2024-07-26 13_05_09-ScreenToGif • Editor](https://github.com/user-attachments/assets/6edbbd18-8d96-46a3-9b07-764db23600fd)
